/**
 * ElevenLabs preset voices available through Kie (same list for Turbo 2.5, Multilingual v2 and Dialogue v3).
 * From docs.kie.ai/market/elevenlabs on 2026-09-25. Descriptions are Kie's, cut short where the docs wrap.
 * Preview: https://static.aiquickdraw.com/elevenlabs/voice/<id>.mp3
 */
export const ELEVENLABS_VOICES: { id: string; name: string; description: string }[] = [
  { id: "eR40ATw9ArzDf9h3v7t7", name: "Addison 2.0", description: "Australian" },
  { id: "5l5f8iK3YPeGga21rQIX", name: "Adeline", description: "Feminine" },
  { id: "1wGbFxmAM3Fgw63G1zZJ", name: "Allison", description: "Calm, Soothing" },
  { id: "wJqPPQ618aTW29mptyoc", name: "Ana Rita", description: "Smooth, Expressive" },
  { id: "Sm1seazb4gs7RSlUVw7c", name: "Anika", description: "Animated, Friendly" },
  { id: "Z3R5wn05IrDiVCyEkUrK", name: "Arabella", description: "Mysterious and Emotive" },
  { id: "TC0Zp7WVFzhA8zpTlRqV", name: "Aria", description: "Sultry Villain" },
  { id: "hpp4J3VqNfWAUOO0d1Us", name: "Bella", description: "Professional, Bright" },
  { id: "LruHrtVF6PSyGItzMNHS", name: "Benjamin", description: "Deep, Warm, Calming" },
  { id: "NNl6r8mD7vthiJatiJt1", name: "Bradford", description: "Expressive" },
  { id: "nPczCjzI2devNBz1zQrb", name: "Brian", description: "Deep, Resonant" },
  { id: "gU0LNdkMOQCOrPrwtbee", name: "British Football Announcer", description: "" },
  { id: "esy0r39YPLQjOczyOib8", name: "Britney", description: "Calm and Calculative" },
  { id: "kPzsL2i3teMYv0FxEYQ6", name: "Brittney", description: "Social Media Voice" },
  { id: "DGzg6RaUqxGRTHSBjfgF", name: "Brock", description: "Commanding and Loud" },
  { id: "4YYIPFl9wE5c4L2eu2Gb", name: "Burt Reynolds™", description: "Deep, Smooth" },
  { id: "N2lVS1w4EtoT3dr4eOWO", name: "Callum", description: "Husky Trickster" },
  { id: "56AoDkrOh6qfVPDXZ7Pt", name: "Cassidy", description: "Crisp, Direct and Clear" },
  { id: "dHd5gvgSOzSfduK4CvEg", name: "Ed", description: "Late Night Announcer" },
  { id: "zYcjlYFOd3taleS0gkk3", name: "Edward", description: "Loud, Confident" },
  { id: "pPdl9cQBQq4p6mRkZy2Z", name: "Emma", description: "Adorable and Upbeat" },
  { id: "BZgkqPqms7Kj9ulSkVzn", name: "Eve", description: "Authentic, Energetic" },
  { id: "Sq93GQT4X1lKDXsQcixO", name: "Felix", description: "Warm, Positive" },
  { id: "vBKc2FfBKJfcZNyEt1n6", name: "Finn", description: "Youthful, Eager" },
  { id: "6F5Zhi321D3Oq7v1oNT4", name: "Hank", description: "Deep and Engaging Narrator" },
  { id: "iCrDUkL56s3C8sCRl7wb", name: "Hope", description: "Poetic, Romantic" },
  { id: "uYXf8XasLslADfZ2MB4u", name: "Hope", description: "Bubbly, Gossipy and Girly" },
  { id: "qXpMhyvQqiRxWQs4qSSB", name: "Horatius", description: "Energetic Character" },
  { id: "DTKMou8ccj1ZaWGBiotd", name: "Jamahal", description: "Young, Vibrant," },
  { id: "EkK5I93UQWFDigLMpZcX", name: "James", description: "Husky, Engaging and Bold" },
  { id: "eVItLK1UvXctxuaRV2Oq", name: "Jean", description: "Alluring and Playful Femme" },
  { id: "gs0tAILXbY5DNrJrsM6F", name: "Jeff", description: "Classy, Resonating" },
  { id: "flHkNRp1BlvT73UL6gyz", name: "Jessica Anne Bogart", description: "Eloquent" },
  { id: "g6xIsTj2HwM6VR4iXFCw", name: "Jessica Anne Bogart", description: "Chatty" },
  { id: "EiNlNiXeDU1pqqOPrYMO", name: "John Doe", description: "Deep" },
  { id: "ruirxsoakN0GWmGNIo04", name: "John Morgan", description: "Gritty, Rugged" },
  { id: "CeNX9CMwmxDxUF5Q2Inm", name: "Johnny Dynamite", description: "Vintage Radio" },
  { id: "8JVbfL6oEdmuxKn5DK2C", name: "Johnny Kid", description: "Serious and Calm" },
  { id: "B8gJV1IhpuegLxdpXFOE", name: "Kuon", description: "Cheerful, Clear and Steady" },
  { id: "FGY2WhTYpPnrIDTdsKH5", name: "Laura", description: "Enthusiast, Quirky" },
  { id: "MJ0RnG71ty4LH3dvNfSd", name: "Leon", description: "Soothing and Grounded" },
  { id: "TX3LPaxmHKxFdv7VOQHJ", name: "Liam", description: "Energetic, Social Media" },
  { id: "lcMyyd2HUfFzxdCaC4Ta", name: "Lucy", description: "Fresh & Casual" },
  { id: "9yzdeviXkFddZ4Oz8Mok", name: "Lutz", description: "Chuckling, Giggly" },
  { id: "1SM7GgM6IMuvQlz2BwM3", name: "Mark", description: "Casual, Relaxed and Light" },
  { id: "UgBBYS2sOqTuMpoF3BR0", name: "Mark", description: "Natural Conversations" },
  { id: "nzeAacJi50IvxcyDnMXa", name: "Marshal", description: "Friendly, Funny" },
  { id: "2zRM7PkgwBPiau2jvVXc", name: "Monika Sogam", description: "Deep and Natural" },
  { id: "x70vRnQBMBu4FAYhjJbO", name: "Nathan", description: "Virtual Radio Host" },
  { id: "AeRdCCKzvd23BpJoofzx", name: "Nathaniel", description: "Engaging, British" },
  { id: "wo6udizrrtpIxWGp2qJk", name: "Northern Terry", description: "" },
  { id: "LG95yZDEHg6fCZdQjLqj", name: "Phil", description: "Explosive, Passionate" },
  { id: "PPzYpIqttlTYA83688JI", name: "Pirate Marshal", description: "" },
  { id: "aD6riP1btT197c6dACmy", name: "Rachel M", description: "Pro British Radio" },
  { id: "mtrellq69YZsNwzUSyXh", name: "Rex Thunder", description: "Deep N Tough" },
  { id: "scOwDtmlUjD3prqpp97I", name: "Sam", description: "Support Agent" },
  { id: "NOpBlnGInO9m6vDvFkFC", name: "Spuds Oxley", description: "Wise" },
  { id: "Tsns2HvNFKfGiNjllgqo", name: "Sven", description: "Emotional and Nice" },
  { id: "qDuRKMlYmrm8trt5QyBn", name: "Taksh", description: "Calm, Serious and Smooth" },
  { id: "hqfrgApggtO1785R4Fsn", name: "Theodore HQ", description: "Serene and Grounded" },
  { id: "6aDn1KB0hjpdcocrUkmq", name: "Tiffany", description: "Natural and Welcoming" },
  { id: "DYkrAHD8iwork3YSUBbs", name: "Tom", description: "Conversations & Books" },
  { id: "ljo9gAlSqKOvF6D8sOsX", name: "Viking Bjorn", description: "Epic Medieval" },
  { id: "1U02n4nD6AdIZ9CjF053", name: "Viraj", description: "Smooth and Gentle" },
  { id: "P1bg08DkjqiVEzOn76yG", name: "Viraj", description: "Rich and Soft" },
  { id: "YXpFCvM1S3JbWEJhoskW", name: "Wyatt", description: "Wise Rustic Cowboy" },
  { id: "YOq2y2Up4RgXP2HyXjE5", name: "Xavier", description: "Dominating, Metallic" },
];

/** Kie's default voice (James). */
export const DEFAULT_ELEVENLABS_VOICE = "EkK5I93UQWFDigLMpZcX";
